### ISSUE TITLE
 Can't download  Posestimates.pkl

### ISSUE THREAD

**Issue by lzfff12** [facebookresearch/ContactOpt#5]
Can someone give me another way to download it

**Comment by pgrady3** [comment]
The dropbox link in the installation readme should work! https://www.dropbox.com/s/349xj3bu446mmgw/pose_estimates.pkl?dl=0

**Comment by lzfff12** [comment]
I tried again, but when I was almost finished downloading it, it had the error shown below
![image](https://user-images.githubusercontent.com/55379485/161571636-24b93f04-66de-40e7-8b1a-42791d9abcb3.png)
it tell that an error occurred while creating a secure connection

**Comment by pgrady3** [comment]
Here's a new link (that won't work after a month) to download the pose_estimates file.

https://gatech.box.com/v/contactopt-pose-estimates

**Comment by lzfff12** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/ContactOpt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 凌晨1:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/ContactOpt]  Can't download  Posestimates.pkl (Issue #5)





 
Here's a new link (that won't work after a month) to download the pose_estimates file.
 
https://gatech.box.com/v/contactopt-pose-estimates
